'use client'

import { useEffect, useState } from 'react'
import { TreemapVisualization } from '@/components/TreemapVisualization'
import { Footer } from '@/components/Footer'

interface Occupation {
  anzsco_code: string
  title: string
  employment: number
  median_pay_aud: number
  ai_exposure: number
  outlook: string
  source: string
}

export default function Home() {
  const [occupations, setOccupations] = useState<Occupation[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    const API_URL = 'https://taskfolio-au-api.hello-bb8.workers.dev'
    fetch(`${API_URL}/api/occupations`)
      .then(res => res.json())
      .then(data => {
        setOccupations(data)
        setLoading(false)
      })
      .catch(err => {
        setError(err.message)
        setLoading(false)
      })
  }, [])

  if (loading) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-bg p-4" role="status" aria-live="polite">
        <div className="card-brutal p-6 brutal-hover">
          <span className="sr-only">Loading</span>
          <p className="font-bold text-lg">Loading occupations...</p>
        </div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-bg p-4" role="alert">
        <div className="card-brutal p-6 bg-danger">
          <p className="font-bold">Error: {error}</p>
        </div>
      </div>
    )
  }

  return (
    <main className="min-h-screen bg-bg">
      <div className="mx-auto max-w-7xl px-3 py-4 sm:px-6 sm:py-8 lg:px-8">
        {/* Hero Header */}
        <header className="mb-4 sm:mb-8 card-brutal p-4 sm:p-6 bg-main">
          <h1 className="text-2xl sm:text-4xl lg:text-5xl font-extrabold tracking-tight text-black">
            TASKFOLIO
          </h1>
          <p className="mt-2 sm:mt-3 text-sm sm:text-lg font-medium text-black">
            See exactly which parts of your job AI will affect — task by task, with timeframes.
          </p>
          <div className="mt-3 sm:mt-4 flex flex-wrap gap-2" aria-live="polite">
            <span className="badge-brutal bg-white text-[10px] sm:text-xs">
              {occupations.length} occupations
            </span>
            <span className="badge-brutal bg-white text-[10px] sm:text-xs">
              6,690 tasks
            </span>
            <span className="badge-brutal bg-white text-[10px] sm:text-xs hidden sm:inline-flex">
              Click to explore
            </span>
            <span className="badge-brutal bg-white text-[10px] sm:text-xs sm:hidden">
              Tap to explore
            </span>
          </div>
        </header>

        {/* Disclaimer */}
        <details className="mb-4 sm:mb-6 card-brutal p-3 sm:p-4 bg-gray-50">
          <summary className="cursor-pointer font-bold text-sm sm:text-base text-black/80 hover:text-black">
            ⚠️ About this data & methodology
          </summary>
          <div className="mt-3 space-y-3 text-xs sm:text-sm text-black/70">
            <p>
              <strong>This is a research tool, not a prediction.</strong> TaskFolio visualizes 361 Australian occupations 
              and 6,690 tasks to explore how AI might reshape work. It is not a report, a paper, or career advice — 
              it is a development tool for exploring AI exposure visually.
            </p>
            <p>
              <strong>AI Exposure scores are LLM estimates.</strong> We use data from the{' '}
              <a href="https://www.anthropic.com/research/anthropic-economic-index-january-2026-report" target="_blank" rel="noopener noreferrer" className="link-brutal">
                Anthropic Economic Index
              </a>{' '}
              (1M real AI conversations) combined with{' '}
              <a href="https://www.onetonline.org/" target="_blank" rel="noopener noreferrer" className="link-brutal">
                O*NET
              </a>{' '}
              task descriptions, mapped to Australian ANZSCO occupations. For unmapped occupations, 
              tasks were generated by Claude with Australian regulatory context.
            </p>
            <p>
              <strong>High exposure ≠ job disappears.</strong> Software developers score high because AI is 
              transforming their work — but demand for software could grow as each developer becomes more productive. 
              Scores don't account for demand elasticity, latent demand, regulatory barriers, or social preferences 
              for human workers. Many high-exposure jobs will be <em>reshaped</em>, not replaced.
            </p>
            <p>
              <strong>Employment projections from JSA.</strong> The "Employment Outlook" section uses official 
              10-year projections from{' '}
              <a href="https://www.jobsandskills.gov.au/data/employment-projections" target="_blank" rel="noopener noreferrer" className="link-brutal">
                Jobs and Skills Australia
              </a>{' '}
              (May 2025 → May 2035). These are trend-based projections, not forecasts — they don't yet reflect 
              generative AI's labour market implications.
            </p>
            <p className="text-black/50">
              Full methodology and data sources:{' '}
              <a href="/legal/attribution" className="link-brutal">Attribution</a>
              {' • '}
              <a href="https://github.com/suryast/task-folio/blob/main/docs/METHODOLOGY.md" target="_blank" rel="noopener noreferrer" className="link-brutal">
                METHODOLOGY.md
              </a>
            </p>
          </div>
        </details>

        {/* Treemap Section */}
        <section aria-label="Occupation treemap visualization">
          <TreemapVisualization occupations={occupations} />
        </section>

        {/* Footer */}
        <Footer />
      </div>
    </main>
  )
}
