"""Report generation: Markdown and self-contained HTML."""
from __future__ import annotations

from datetime import datetime
from string import Template


def generate_markdown(profile: dict) -> str:
    """Generate a Markdown report."""
    score = profile.get("score", {})
    
    lines = [
        f"# Personal AI Exposure Report",
        f"",
        f"**Occupation:** {profile['anzsco_title']} (ANZSCO {profile['anzsco_code']})",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"",
        f"## Summary",
        f"",
        f"- **Overall Exposure:** {score.get('overall_exposure', 0):.1%}",
        f"- **Automation Risk:** {score.get('automation_weighted', 0):.1%}",
        f"- **Augmentation Potential:** {score.get('augmentation_weighted', 0):.1%}",
        f"",
        f"**Tasks analyzed:** {profile['tasks_selected']} of {profile['total_tasks_available']} available",
        f"",
    ]
    
    # Timeframe breakdown
    timeframes = score.get("timeframe_breakdown", {})
    if timeframes:
        lines.extend([
            f"## Timeline Breakdown",
            f"",
            f"Percentage of your time spent on tasks expected to be affected in each timeframe:",
            f"",
        ])
        for tf in ["now", "1-2y", "3-5y", "5-10y", "10y+"]:
            if tf in timeframes:
                pct = timeframes[tf]
                lines.append(f"- **{tf}:** {pct:.1f}%")
        lines.append("")
    
    # Task details
    if profile["selected_tasks"]:
        lines.extend([
            f"## Your Tasks",
            f"",
            f"| Task | Time % | Auto | Aug | Timeframe |",
            f"|------|--------|------|-----|-----------|",
        ])
        for task in profile["selected_tasks"]:
            desc = task["task_description"][:50] + "..." if len(task["task_description"]) > 50 else task["task_description"]
            lines.append(
                f"| {desc} | {task['time_pct']:.0f}% | {task['automation_pct']:.1%} | {task['augmentation_pct']:.1%} | {task.get('timeframe', 'unknown')} |"
            )
        lines.append("")
    
    # Enrichment section
    if "enrichment" in profile:
        enrichment = profile["enrichment"]
        lines.extend([
            f"## AI-Enhanced Insights",
            f"",
        ])
        
        if "workplace_context" in enrichment:
            lines.extend([
                f"**Workplace Context:** {enrichment['workplace_context']}",
                f"",
            ])
        
        if "custom_tasks" in enrichment and enrichment["custom_tasks"]:
            lines.extend([
                f"**Additional tasks you might do:**",
                f"",
            ])
            for task in enrichment["custom_tasks"]:
                lines.append(f"- {task}")
            lines.append("")
        
        if "risk_adjustments" in enrichment and enrichment["risk_adjustments"]:
            lines.extend([
                f"**Personalized risk adjustments:**",
                f"",
            ])
            for task_key, adj in enrichment["risk_adjustments"].items():
                if isinstance(adj, dict):
                    adjustment = adj.get("adjustment", 0)
                    rationale = adj.get("rationale", "")
                    lines.append(f"- {rationale} (adjustment: {adjustment:+.1%})")
            lines.append("")
    
    lines.extend([
        f"---",
        f"",
        f"*Generated by [TaskFolio Personal Risk Profiler](https://taskfolio.ai)*",
    ])
    
    return "\n".join(lines)


def generate_html(profile: dict) -> str:
    """Generate a self-contained HTML report with neobrutal styling."""
    score = profile.get("score", {})
    
    # Build task rows
    task_rows = []
    for task in profile["selected_tasks"]:
        desc = task["task_description"]
        task_rows.append(f"""
            <tr>
                <td>{desc}</td>
                <td>{task['time_pct']:.0f}%</td>
                <td>{task['automation_pct']:.1%}</td>
                <td>{task['augmentation_pct']:.1%}</td>
                <td>{task.get('timeframe', 'unknown')}</td>
            </tr>
        """)
    
    # Build timeframe bars
    timeframes = score.get("timeframe_breakdown", {})
    timeframe_bars = []
    for tf in ["now", "1-2y", "3-5y", "5-10y", "10y+"]:
        if tf in timeframes:
            pct = timeframes[tf]
            timeframe_bars.append(f"""
                <div class="timeframe-item">
                    <div class="timeframe-label">{tf}</div>
                    <div class="bar-container">
                        <div class="bar" style="width: {pct}%"></div>
                    </div>
                    <div class="timeframe-value">{pct:.1f}%</div>
                </div>
            """)
    
    # Enrichment section
    enrichment_html = ""
    if "enrichment" in profile:
        enrichment = profile["enrichment"]
        sections = []
        
        if "workplace_context" in enrichment:
            sections.append(f"""
                <div class="card">
                    <h3>💼 Workplace Context</h3>
                    <p>{enrichment['workplace_context']}</p>
                </div>
            """)
        
        if "custom_tasks" in enrichment and enrichment["custom_tasks"]:
            tasks_list = "".join(f"<li>{task}</li>" for task in enrichment["custom_tasks"])
            sections.append(f"""
                <div class="card">
                    <h3>✨ Additional Tasks</h3>
                    <ul>{tasks_list}</ul>
                </div>
            """)
        
        if "risk_adjustments" in enrichment and enrichment["risk_adjustments"]:
            adjustments_list = []
            for task_key, adj in enrichment["risk_adjustments"].items():
                if isinstance(adj, dict):
                    adjustment = adj.get("adjustment", 0)
                    rationale = adj.get("rationale", "")
                    sign = "+" if adjustment >= 0 else ""
                    adjustments_list.append(f"<li>{rationale} ({sign}{adjustment:.1%})</li>")
            if adjustments_list:
                sections.append(f"""
                    <div class="card">
                        <h3>🎯 Personalized Adjustments</h3>
                        <ul>{"".join(adjustments_list)}</ul>
                    </div>
                """)
        
        if sections:
            enrichment_html = f"""
                <section class="enrichment">
                    <h2>🤖 AI-Enhanced Insights</h2>
                    {"".join(sections)}
                </section>
            """
    
    template = Template("""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Exposure Report - $title</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            background: #fefae0;
            color: #1a1a1a;
            padding: 2rem;
            line-height: 1.6;
        }
        
        .container {
            max-width: 900px;
            margin: 0 auto;
        }
        
        header {
            background: #fff;
            border: 4px solid #1a1a1a;
            box-shadow: 8px 8px 0 #1a1a1a;
            padding: 2rem;
            margin-bottom: 2rem;
        }
        
        h1 {
            font-size: 2rem;
            margin-bottom: 0.5rem;
            font-weight: 900;
            text-transform: uppercase;
        }
        
        .subtitle {
            font-size: 1.2rem;
            color: #666;
            margin-bottom: 0.5rem;
        }
        
        .meta {
            font-size: 0.9rem;
            color: #999;
        }
        
        .summary {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 1rem;
            margin-bottom: 2rem;
        }
        
        .metric-card {
            background: #fff;
            border: 4px solid #1a1a1a;
            box-shadow: 6px 6px 0 #1a1a1a;
            padding: 1.5rem;
        }
        
        .metric-card h3 {
            font-size: 0.9rem;
            text-transform: uppercase;
            color: #666;
            margin-bottom: 0.5rem;
        }
        
        .metric-value {
            font-size: 2.5rem;
            font-weight: 900;
            color: #1a1a1a;
        }
        
        .metric-card.high {
            background: #fecaca;
        }
        
        .metric-card.medium {
            background: #fef08a;
        }
        
        .metric-card.low {
            background: #bbf7d0;
        }
        
        section {
            background: #fff;
            border: 4px solid #1a1a1a;
            box-shadow: 8px 8px 0 #1a1a1a;
            padding: 2rem;
            margin-bottom: 2rem;
        }
        
        h2 {
            font-size: 1.5rem;
            margin-bottom: 1.5rem;
            text-transform: uppercase;
            font-weight: 900;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 1rem;
        }
        
        th {
            background: #1a1a1a;
            color: #fff;
            padding: 0.75rem;
            text-align: left;
            font-weight: 700;
            text-transform: uppercase;
            font-size: 0.85rem;
        }
        
        td {
            padding: 0.75rem;
            border-bottom: 2px solid #e5e5e5;
        }
        
        tr:last-child td {
            border-bottom: none;
        }
        
        .timeframe-item {
            display: grid;
            grid-template-columns: 80px 1fr 60px;
            align-items: center;
            gap: 1rem;
            margin-bottom: 1rem;
        }
        
        .timeframe-label {
            font-weight: 700;
            font-size: 0.9rem;
        }
        
        .bar-container {
            background: #e5e5e5;
            border: 2px solid #1a1a1a;
            height: 32px;
        }
        
        .bar {
            background: #1a1a1a;
            height: 100%;
            transition: width 0.3s ease;
        }
        
        .timeframe-value {
            text-align: right;
            font-weight: 700;
        }
        
        .card {
            background: #f9fafb;
            border: 3px solid #1a1a1a;
            padding: 1.5rem;
            margin-bottom: 1rem;
        }
        
        .card h3 {
            margin-bottom: 1rem;
            font-size: 1.1rem;
        }
        
        .card ul {
            list-style-position: inside;
            margin-left: 1rem;
        }
        
        .card li {
            margin-bottom: 0.5rem;
        }
        
        footer {
            text-align: center;
            color: #666;
            font-size: 0.9rem;
            margin-top: 3rem;
        }
        
        footer a {
            color: #1a1a1a;
            font-weight: 700;
        }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>🎯 Personal AI Exposure Report</h1>
            <div class="subtitle">$title</div>
            <div class="meta">ANZSCO $anzsco_code | Generated $timestamp</div>
        </header>
        
        <div class="summary">
            <div class="metric-card $overall_class">
                <h3>Overall Exposure</h3>
                <div class="metric-value">$overall_pct%</div>
            </div>
            <div class="metric-card $auto_class">
                <h3>Automation Risk</h3>
                <div class="metric-value">$auto_pct%</div>
            </div>
            <div class="metric-card $aug_class">
                <h3>Augmentation Potential</h3>
                <div class="metric-value">$aug_pct%</div>
            </div>
        </div>
        
        <section>
            <h2>📊 Timeline Breakdown</h2>
            <p style="margin-bottom: 1.5rem; color: #666;">
                Percentage of your time spent on tasks expected to be affected in each timeframe
            </p>
            $timeframe_bars
        </section>
        
        <section>
            <h2>📋 Your Tasks</h2>
            <p style="margin-bottom: 1rem; color: #666;">
                Analyzing <strong>$tasks_selected</strong> of <strong>$total_tasks</strong> available tasks
            </p>
            <table>
                <thead>
                    <tr>
                        <th>Task Description</th>
                        <th>Time %</th>
                        <th>Auto</th>
                        <th>Aug</th>
                        <th>Timeframe</th>
                    </tr>
                </thead>
                <tbody>
                    $task_rows
                </tbody>
            </table>
        </section>
        
        $enrichment_section
        
        <footer>
            Generated by <a href="https://taskfolio.ai">TaskFolio Personal Risk Profiler</a>
        </footer>
    </div>
</body>
</html>""")
    
    # Helper function to get color class
    def get_class(value):
        if value >= 0.7:
            return "high"
        elif value >= 0.4:
            return "medium"
        else:
            return "low"
    
    html = template.substitute(
        title=profile['anzsco_title'],
        anzsco_code=profile['anzsco_code'],
        timestamp=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        overall_pct=int(score.get('overall_exposure', 0) * 100),
        overall_class=get_class(score.get('overall_exposure', 0)),
        auto_pct=int(score.get('automation_weighted', 0) * 100),
        auto_class=get_class(score.get('automation_weighted', 0)),
        aug_pct=int(score.get('augmentation_weighted', 0) * 100),
        aug_class=get_class(score.get('augmentation_weighted', 0)),
        timeframe_bars="".join(timeframe_bars),
        tasks_selected=profile['tasks_selected'],
        total_tasks=profile['total_tasks_available'],
        task_rows="".join(task_rows),
        enrichment_section=enrichment_html,
    )
    
    return html
